// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "./notes/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AckTerminalData resumes the reader if its high-watermark pause is in effect.
 * @param {string} id
 * @param {number} charCount
 * @returns {$CancellablePromise<void>}
 */
export function AckTerminalData(id, charCount) {
    return $Call.ByID(1945733426, id, charCount);
}

/**
 * AddPortForward is idempotent on remote port and picks a free local port
 * when localPort=0.
 * @param {string} project
 * @param {number} remotePort
 * @param {number} localPort
 * @returns {$CancellablePromise<$models.PortForward>}
 */
export function AddPortForward(project, remotePort, localPort) {
    return $Call.ByID(212145684, project, remotePort, localPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectName
 * @returns {$CancellablePromise<void>}
 */
export function AttachProject(projectName) {
    return $Call.ByID(542969777, projectName);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseFolder() {
    return $Call.ByID(3225197899);
}

/**
 * @returns {$CancellablePromise<$models.AICLIAvailability>}
 */
export function CheckAICLIs() {
    return $Call.ByID(4200690458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectName
 * @param {string} actionName
 * @returns {$CancellablePromise<$models.PortConflictInfo[]>}
 */
export function CheckActionPortConflict(projectName, actionName) {
    return $Call.ByID(1625607276, projectName, actionName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ClaudeHooksStatus>}
 */
export function CheckClaudeHooks() {
    return $Call.ByID(982529779).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2347956003).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckGHCLI() {
    return $Call.ByID(624267826);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckKokoroInstalled() {
    return $Call.ByID(3185721286);
}

/**
 * @param {string} name
 * @param {string} profile
 * @returns {$CancellablePromise<$models.PortConflictInfo[]>}
 */
export function CheckPortConflicts(name, profile) {
    return $Call.ByID(794417531, name, profile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @param {string[]} services
 * @returns {$CancellablePromise<$models.PortConflictInfo[]>}
 */
export function CheckPortConflictsForServices(name, services) {
    return $Call.ByID(1475097458, name, services).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckoutBranch creates a tracking branch from <remote>/<branch> when
 * remote is non-empty and no local head exists, disambiguating when
 * multiple remotes carry the same short name (DWIM would fail).
 * @param {string} cwd
 * @param {string} branch
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function CheckoutBranch(cwd, branch, remote) {
    return $Call.ByID(4278840505, cwd, branch, remote);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<void>}
 */
export function ClearPortSuggestions(project) {
    return $Call.ByID(89170842, project);
}

/**
 * @param {string} project
 * @param {string} paneID
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function ClearStatus(project, paneID, value) {
    return $Call.ByID(1060890196, project, paneID, value);
}

/**
 * @param {string} cwd
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateBranch(cwd, name) {
    return $Call.ByID(3624428965, cwd, name);
}

/**
 * @param {string} name
 * @param {string} root
 * @returns {$CancellablePromise<void>}
 */
export function CreateProject(name, root) {
    return $Call.ByID(969543070, name, root);
}

/**
 * @param {string} name
 * @param {string} url
 * @param {string} branch
 * @param {string} destParent
 * @returns {$CancellablePromise<void>}
 */
export function CreateProjectFromClone(name, url, branch, destParent) {
    return $Call.ByID(2578662527, name, url, branch, destParent);
}

/**
 * CreatePullRequest pushes the current branch and creates a PR via gh,
 * returning the PR URL on success.
 * @param {string} cwd
 * @param {string} title
 * @param {string} body
 * @param {string} base
 * @returns {$CancellablePromise<string>}
 */
export function CreatePullRequest(cwd, title, body, base) {
    return $Call.ByID(1615550643, cwd, title, body, base);
}

/**
 * @param {string} name
 * @param {$models.SSHConfig} ssh
 * @returns {$CancellablePromise<void>}
 */
export function CreateSSHProject(name, ssh) {
    return $Call.ByID(2519723066, name, ssh);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateTemplate(name) {
    return $Call.ByID(2495736427, name);
}

/**
 * DeleteBranch uses -D (force) so unmerged branches can be dropped —
 * the UI confirms before calling.
 * @param {string} cwd
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBranch(cwd, name) {
    return $Call.ByID(308689290, cwd, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTemplate(name) {
    return $Call.ByID(3301115428, name);
}

/**
 * DetachProject opens (or focuses) a dedicated window. The detached state
 * persists so the window auto-reopens on next launch.
 * @param {string} projectName
 * @returns {$CancellablePromise<void>}
 */
export function DetachProject(projectName) {
    return $Call.ByID(448133659, projectName);
}

/**
 * @param {string} project
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function DismissPortSuggestion(project, port) {
    return $Call.ByID(1442051968, project, port);
}

/**
 * DuplicateProject copies the folder literally (including .git and node_modules).
 * parent_name always points at the original — duplicate chains collapse to the
 * root parent so the lpm config stays shared. excludeUncommitted resets the new
 * copy to HEAD, discarding tracked/untracked changes; ignored files survive.
 * @param {string} name
 * @param {boolean} excludeUncommitted
 * @returns {$CancellablePromise<string>}
 */
export function DuplicateProject(name, excludeUncommitted) {
    return $Call.ByID(3548434383, name, excludeUncommitted);
}

/**
 * ExportConfig writes a tar.gz of the portable portion of ~/.lpm. Notes
 * are excluded — users transport them via Export/Import vault key plus a
 * manual copy of ~/.lpm/notes/. Uses OpenDirectoryDialog because
 * SaveFileDialog is flaky on newer macOS.
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig() {
    return $Call.ByID(2222068969);
}

/**
 * @param {string} absPath
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(absPath) {
    return $Call.ByID(2577714203, absPath);
}

/**
 * FocusDetachedWindow returns false if the project is not currently detached.
 * @param {string} projectName
 * @returns {$CancellablePromise<boolean>}
 */
export function FocusDetachedWindow(projectName) {
    return $Call.ByID(2912316637, projectName);
}

/**
 * GenerateActionYAML: empty currentYAML produces a fresh action; non-empty
 * asks the AI to modify it in place.
 * @param {string} projectName
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @param {string} userPrompt
 * @param {string} currentYAML
 * @returns {$CancellablePromise<string>}
 */
export function GenerateActionYAML(projectName, cli, model, effort, fast, userPrompt, currentYAML) {
    return $Call.ByID(3869703943, projectName, cli, model, effort, fast, userPrompt, currentYAML);
}

/**
 * GenerateBranchName falls back to the current branch diff against the
 * default branch when no uncommitted changes are present.
 * @param {string} cwd
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @returns {$CancellablePromise<string>}
 */
export function GenerateBranchName(cwd, cli, model, effort, fast) {
    return $Call.ByID(242576153, cwd, cli, model, effort, fast);
}

/**
 * GenerateCommitMessage: effort "" uses the CLI default; fast enables
 * Codex's service_tier=fast and is ignored for other CLIs.
 * @param {string} cwd
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @param {string[]} files
 * @returns {$CancellablePromise<string>}
 */
export function GenerateCommitMessage(cwd, cli, model, effort, fast, files) {
    return $Call.ByID(1669373286, cwd, cli, model, effort, fast, files);
}

/**
 * @param {string} cwd
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @param {string} base
 * @returns {$CancellablePromise<string>}
 */
export function GeneratePRDescription(cwd, cli, model, effort, fast, base) {
    return $Call.ByID(2319699198, cwd, cli, model, effort, fast, base);
}

/**
 * @param {string} cwd
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @param {string} base
 * @returns {$CancellablePromise<string>}
 */
export function GeneratePRTitle(cwd, cli, model, effort, fast, base) {
    return $Call.ByID(1596847202, cwd, cli, model, effort, fast, base);
}

/**
 * @param {string} projectName
 * @param {string} cli
 * @param {string} extraPrompt
 * @returns {$CancellablePromise<string>}
 */
export function GenerateProjectConfig(projectName, cli, extraPrompt) {
    return $Call.ByID(662009385, projectName, cli, extraPrompt);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetPlatform() {
    return $Call.ByID(3709063056);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function GetProject(name) {
    return $Call.ByID(4040571020, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} projectName
 * @param {number} paneIndex
 * @param {number} lines
 * @returns {$CancellablePromise<string>}
 */
export function GetServiceLogs(projectName, paneIndex, lines) {
    return $Call.ByID(4253359345, projectName, paneIndex, lines);
}

/**
 * GetSuggestedPorts lets the popover render suggestions when the toast
 * was lost (e.g. emitted before the listener mounted).
 * @param {string} project
 * @returns {$CancellablePromise<number[]>}
 */
export function GetSuggestedPorts(project) {
    return $Call.ByID(2854026930, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function GitAbortMerge(cwd) {
    return $Call.ByID(2106669349, cwd);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<$models.ChangedFile[]>}
 */
export function GitChangedFiles(cwd) {
    return $Call.ByID(936011668, cwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} cwd
 * @param {string} message
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function GitCommit(cwd, message, files) {
    return $Call.ByID(1971060042, cwd, message, files);
}

/**
 * GitCommitCount returns commits reachable from `to` but not from `from`,
 * or 0 on any git error so callers don't have to handle it for a hint UI.
 * @param {string} cwd
 * @param {string} $from
 * @param {string} to
 * @returns {$CancellablePromise<number>}
 */
export function GitCommitCount(cwd, $from, to) {
    return $Call.ByID(1259249825, cwd, $from, to);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<string>}
 */
export function GitDefaultBranch(cwd) {
    return $Call.ByID(2805332012, cwd);
}

/**
 * GitDiff returns the combined diff; untracked files are shown as an "add" diff.
 * @param {string} cwd
 * @param {string[]} files
 * @returns {$CancellablePromise<string>}
 */
export function GitDiff(cwd, files) {
    return $Call.ByID(4088799792, cwd, files);
}

/**
 * @param {string} cwd
 * @param {string} base
 * @returns {$CancellablePromise<string>}
 */
export function GitDiffBranch(cwd, base) {
    return $Call.ByID(2325957792, cwd, base);
}

/**
 * GitDiscardAll discards every uncommitted change; ignored files are preserved.
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function GitDiscardAll(cwd) {
    return $Call.ByID(339749546, cwd);
}

/**
 * GitDiscardFiles drops uncommitted changes for the given paths. Tracked
 * files are restored to HEAD; untracked files are removed via `git clean`
 * which honors .gitignore so ignored paths are preserved.
 * @param {string} cwd
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function GitDiscardFiles(cwd, files) {
    return $Call.ByID(3940760550, cwd, files);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function GitFetchAll(cwd) {
    return $Call.ByID(3598362604, cwd);
}

/**
 * @param {string} cwd
 * @param {string} base
 * @returns {$CancellablePromise<$models.BranchCommit[]>}
 */
export function GitLogBranch(cwd, base) {
    return $Call.ByID(2012203595, cwd, base).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GitMerge requires a fully qualified ref the caller resolved (e.g. "origin/feature-x").
 * @param {string} cwd
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function GitMerge(cwd, branch) {
    return $Call.ByID(2900536833, cwd, branch);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<string[]>}
 */
export function GitMergeConflicts(cwd) {
    return $Call.ByID(2414979136, cwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function GitPush(cwd) {
    return $Call.ByID(4036251239, cwd);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function GitStatus(cwd) {
    return $Call.ByID(1421317957, cwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ImportConfig snapshots the current config, then merges the archive in.
 * When overwrite is false, existing projects are kept and reported as Skipped.
 * @param {boolean} overwrite
 * @returns {$CancellablePromise<$models.ImportReport | null>}
 */
export function ImportConfig(overwrite) {
    return $Call.ByID(3706958138, overwrite).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InstallKokoro() {
    return $Call.ByID(3859758367);
}

/**
 * InstallTmux streams Homebrew progress via "tmux-install-output" events.
 * @returns {$CancellablePromise<void>}
 */
export function InstallTmux() {
    return $Call.ByID(3413927782);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(2443992793);
}

/**
 * IsTerminalRemote is false for unknown ids, local panes, and sync-mode panes.
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function IsTerminalRemote(id) {
    return $Call.ByID(2381791855, id);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<$models.Branch[]>}
 */
export function ListBranches(cwd) {
    return $Call.ByID(3649264093, cwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDetachedProjects() {
    return $Call.ByID(3466390445).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.OpenInTarget[]>}
 */
export function ListOpenInTargets() {
    return $Call.ByID(2038005764).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<$models.PortForward[]>}
 */
export function ListPortForwards(project) {
    return $Call.ByID(301106700, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectInfo[]>}
 */
export function ListProjects() {
    return $Call.ByID(2721360259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * ListSSHHosts returns non-wildcard hosts from ~/.ssh/config and any
 * Include'd files; missing config is not an error.
 * @returns {$CancellablePromise<$models.SSHConfigHost[]>}
 */
export function ListSSHHosts() {
    return $Call.ByID(2197797244).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TemplateInfo[]>}
 */
export function ListTemplates() {
    return $Call.ByID(479751508).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function LoadSettings() {
    return $Call.ByID(3551729052).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TerminalsConfig>}
 */
export function LoadTerminals() {
    return $Call.ByID(126578114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * NotesAddMessage: on failure, successfully-written blobs may remain as
 * orphans until the next delete GCs them.
 * @param {string} project
 * @param {string} chatID
 * @param {string} text
 * @param {$models.NotesAttachmentInput[]} attachments
 * @returns {$CancellablePromise<notes$0.Message | null>}
 */
export function NotesAddMessage(project, chatID, text, attachments) {
    return $Call.ByID(2002640880, project, chatID, text, attachments).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * @param {string} project
 * @param {string} title
 * @returns {$CancellablePromise<notes$0.Chat | null>}
 */
export function NotesCreateChat(project, title) {
    return $Call.ByID(1749832808, project, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * @param {string} project
 * @param {string} chatID
 * @returns {$CancellablePromise<void>}
 */
export function NotesDeleteChat(project, chatID) {
    return $Call.ByID(2371248755, project, chatID);
}

/**
 * @param {string} project
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function NotesDeleteMessage(project, id) {
    return $Call.ByID(103754972, project, id);
}

/**
 * @param {string} project
 * @param {string} id
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function NotesEditMessage(project, id, text) {
    return $Call.ByID(264940781, project, id, text);
}

/**
 * @param {string} project
 * @returns {$CancellablePromise<notes$0.Chat[]>}
 */
export function NotesListChats(project) {
    return $Call.ByID(13438921, project).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @param {string} project
 * @param {string} chatID
 * @param {number} limit
 * @param {string} beforeID
 * @returns {$CancellablePromise<notes$0.Message[]>}
 */
export function NotesListMessages(project, chatID, limit, beforeID) {
    return $Call.ByID(2928639434, project, chatID, limit, beforeID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * NotesReadAttachment returns base64; see NotesAttachmentInput for rationale.
 * @param {string} project
 * @param {string} hash
 * @returns {$CancellablePromise<string>}
 */
export function NotesReadAttachment(project, hash) {
    return $Call.ByID(900765911, project, hash);
}

/**
 * NotesReadFileAsInput: Wails delivers OS file paths rather than File blobs
 * for native drag-and-drop, so we read it ourselves.
 * @param {string} path
 * @returns {$CancellablePromise<$models.NotesAttachmentInput | null>}
 */
export function NotesReadFileAsInput(path) {
    return $Call.ByID(3331712896, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @param {string} project
 * @param {string} chatID
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function NotesRenameChat(project, chatID, title) {
    return $Call.ByID(633744986, project, chatID, title);
}

/**
 * NotesSaveAttachment uses OpenDirectoryDialog because native SaveFileDialog
 * is flaky on newer macOS. Returns "" when the dialog is cancelled.
 * @param {string} project
 * @param {string} hash
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function NotesSaveAttachment(project, hash, name) {
    return $Call.ByID(613714794, project, hash, name);
}

/**
 * @param {string} project
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<notes$0.SearchHit[]>}
 */
export function NotesSearch(project, query, limit) {
    return $Call.ByID(2624176010, project, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * OpenFileInEditor jumps to line:col when both positive. Empty editorID
 * auto-picks the first installed editor with file-level open support,
 * falling back to `open path`.
 * @param {string} editorID
 * @param {string} absPath
 * @param {number} line
 * @param {number} col
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileInEditor(editorID, absPath, line, col) {
    return $Call.ByID(3278715317, editorID, absPath, line, col);
}

/**
 * @param {string} targetID
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenIn(targetID, projectPath) {
    return $Call.ByID(3677882162, targetID, projectPath);
}

/**
 * @param {string} absPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenPathInDefaultApp(absPath) {
    return $Call.ByID(3111990213, absPath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseTTS() {
    return $Call.ByID(65387314);
}

/**
 * @param {string} cwd
 * @param {string} strategy
 * @returns {$CancellablePromise<void>}
 */
export function PullBranch(cwd, strategy) {
    return $Call.ByID(1254511478, cwd, strategy);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadBranchNameInstructions() {
    return $Call.ByID(1657127971);
}

/**
 * ReadClipboardFiles returns nil when the clipboard has no file references.
 * @returns {$CancellablePromise<string[]>}
 */
export function ReadClipboardFiles() {
    return $Call.ByID(2636780132).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadCommitInstructions() {
    return $Call.ByID(1357722845);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ReadConfig(name) {
    return $Call.ByID(1971539327, name);
}

/**
 * @param {string} absPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(absPath) {
    return $Call.ByID(1160596971, absPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadGlobalConfig() {
    return $Call.ByID(443693920);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadPRDescriptionInstructions() {
    return $Call.ByID(2203850638);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadPRTitleInstructions() {
    return $Call.ByID(3279032194);
}

/**
 * ReadRepoConfig returns "" when <root>/.lpm.yml is missing so the editor
 * opens as a blank canvas.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ReadRepoConfig(name) {
    return $Call.ByID(4204720727, name);
}

/**
 * ReadTemplate returns "" for a not-yet-existing template so the editor
 * opens it as a blank canvas after CreateTemplate.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ReadTemplate(name) {
    return $Call.ByID(3034447251, name);
}

/**
 * RemovePortForward is a no-op for unknown local ports.
 * @param {string} project
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function RemovePortForward(project, localPort) {
    return $Call.ByID(1912687307, project, localPort);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(name) {
    return $Call.ByID(66093214, name);
}

/**
 * @param {string} cwd
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameBranch(cwd, oldName, newName) {
    return $Call.ByID(355952819, cwd, oldName, newName);
}

/**
 * RenameTemplate does not rewrite `extends:` refs in other configs — they're
 * keyed by name and would silently break. Callers must warn the user first.
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTemplate(oldName, newName) {
    return $Call.ByID(4244672361, oldName, newName);
}

/**
 * @param {string[]} order
 * @returns {$CancellablePromise<void>}
 */
export function ReorderProjects(order) {
    return $Call.ByID(740296242, order);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetClaudeHooks() {
    return $Call.ByID(4104506458);
}

/**
 * @param {string} id
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(id, cols, rows) {
    return $Call.ByID(1887984285, id, cols, rows);
}

/**
 * ResolveMergeConflictsWithAI runs the CLI with file-write permissions.
 * @param {string} cwd
 * @param {string} cli
 * @param {string} model
 * @param {string} effort
 * @param {boolean} fast
 * @returns {$CancellablePromise<string>}
 */
export function ResolveMergeConflictsWithAI(cwd, cli, model, effort, fast) {
    return $Call.ByID(1955621758, cwd, cli, model, effort, fast);
}

/**
 * @param {$models.PortConflictInfo} c
 * @returns {$CancellablePromise<void>}
 */
export function ResolvePortConflict(c) {
    return $Call.ByID(1922927150, c);
}

/**
 * RestoreDetachedWindows pre-populates the registry under a single lock so
 * any early ListDetachedProjects observes the final set.
 * @returns {$CancellablePromise<void>}
 */
export function RestoreDetachedWindows() {
    return $Call.ByID(148991908);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResumeTTS() {
    return $Call.ByID(2700412163);
}

/**
 * RunAction returns once the process has started; output streams via events.
 * @param {string} projectName
 * @param {string} actionName
 * @param {{ [_ in string]?: string }} inputValues
 * @returns {$CancellablePromise<void>}
 */
export function RunAction(projectName, actionName, inputValues) {
    return $Call.ByID(1471119456, projectName, actionName, inputValues);
}

/**
 * RunActionBackground blocks until the command exits. On failure, the
 * returned error includes a trimmed tail of combined output.
 * @param {string} projectName
 * @param {string} actionName
 * @param {{ [_ in string]?: string }} inputValues
 * @returns {$CancellablePromise<void>}
 */
export function RunActionBackground(projectName, actionName, inputValues) {
    return $Call.ByID(3891480868, projectName, actionName, inputValues);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveBranchNameInstructions(content) {
    return $Call.ByID(359969646, content);
}

/**
 * SaveClipboardImage writes base64-encoded data to a temp file so a
 * clipboard image paste can be inserted into the terminal as a file path.
 * @param {string} b64Data
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function SaveClipboardImage(b64Data, mimeType) {
    return $Call.ByID(3932748547, b64Data, mimeType);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveCommitInstructions(content) {
    return $Call.ByID(3381428604, content);
}

/**
 * SaveConfig returns the name the frontend should stay on. Rename via `name:`
 * is rejected while duplicates exist (cascade rename not yet supported).
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveConfig(name, content) {
    return $Call.ByID(3442292638, name, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveGlobalConfig(content) {
    return $Call.ByID(2503806773, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SavePRDescriptionInstructions(content) {
    return $Call.ByID(2314302273, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SavePRTitleInstructions(content) {
    return $Call.ByID(3018700457, content);
}

/**
 * SaveRepoConfig validates against RepoConfig (no name/root/ssh fields).
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveRepoConfig(name, content) {
    return $Call.ByID(2211827642, name, content);
}

/**
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(s) {
    return $Call.ByID(1949631069, s);
}

/**
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveTemplate(name, content) {
    return $Call.ByID(562885018, name, content);
}

/**
 * @param {$models.TerminalsConfig} c
 * @returns {$CancellablePromise<void>}
 */
export function SaveTerminals(c) {
    return $Call.ByID(3362831473, c);
}

/**
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SaveWindowSize(width, height) {
    return $Call.ByID(4029391749, width, height);
}

/**
 * @param {string} cwd
 * @param {string} query
 * @returns {$CancellablePromise<$models.Branch[]>}
 */
export function SearchBranches(cwd, query) {
    return $Call.ByID(429127157, cwd, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * SetProjectLabel: empty clears the label so the identifier name is used.
 * @param {string} name
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function SetProjectLabel(name, label) {
    return $Call.ByID(3010032406, name, label);
}

/**
 * @param {string} projectName
 * @returns {$CancellablePromise<void>}
 */
export function StartLogStreaming(projectName) {
    return $Call.ByID(4078399921, projectName);
}

/**
 * @param {string} name
 * @param {string} profile
 * @returns {$CancellablePromise<void>}
 */
export function StartProject(name, profile) {
    return $Call.ByID(4230643172, name, profile);
}

/**
 * StartProjectWithServices bypasses profile resolution.
 * @param {string} name
 * @param {string[]} services
 * @returns {$CancellablePromise<void>}
 */
export function StartProjectWithServices(name, services) {
    return $Call.ByID(764012756, name, services);
}

/**
 * @param {string} projectName
 * @param {number} paneIndex
 * @returns {$CancellablePromise<void>}
 */
export function StartService(projectName, paneIndex) {
    return $Call.ByID(293702714, projectName, paneIndex);
}

/**
 * StartTTS reads voice and speed from saved settings.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function StartTTS(text) {
    return $Call.ByID(1951683180, text);
}

/**
 * @param {string} projectName
 * @returns {$CancellablePromise<string>}
 */
export function StartTerminal(projectName) {
    return $Call.ByID(3009548683, projectName);
}

/**
 * StartTerminalForConfig runs cmd through the resume registry. For an
 * unrecognised program, ResumeCmd is empty and the caller should not persist
 * either field.
 * @param {string} projectName
 * @param {string} terminalName
 * @returns {$CancellablePromise<$models.TerminalLaunch>}
 */
export function StartTerminalForConfig(projectName, terminalName) {
    return $Call.ByID(2731415512, projectName, terminalName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * StartTerminalForRestore skips the port check and resume-id rewrite, and
 * falls back to a plain shell if the action was renamed or removed since persist.
 * @param {string} projectName
 * @param {string} terminalName
 * @returns {$CancellablePromise<string>}
 */
export function StartTerminalForRestore(projectName, terminalName) {
    return $Call.ByID(1264600188, projectName, terminalName);
}

/**
 * StartTerminalWithCwdEnv: cwd is project-relative; SSH projects resolve
 * it against ssh.dir.
 * @param {string} projectName
 * @param {string} cwd
 * @param {{ [_ in string]?: string }} env
 * @returns {$CancellablePromise<string>}
 */
export function StartTerminalWithCwdEnv(projectName, cwd, env) {
    return $Call.ByID(379050710, projectName, cwd, env);
}

/**
 * StartWatchingProject is a no-op for the same path; empty path stops watching.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function StartWatchingProject(path) {
    return $Call.ByID(1066466243, path);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(1829082188);
}

/**
 * @param {string} projectName
 * @returns {$CancellablePromise<void>}
 */
export function StopLogStreaming(projectName) {
    return $Call.ByID(3622791455, projectName);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function StopProject(name) {
    return $Call.ByID(921119750, name);
}

/**
 * StopService leaves the pane and log history intact.
 * @param {string} projectName
 * @param {number} paneIndex
 * @returns {$CancellablePromise<void>}
 */
export function StopService(projectName, paneIndex) {
    return $Call.ByID(3442034300, projectName, paneIndex);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopTTS() {
    return $Call.ByID(2529096346);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopTerminal(id) {
    return $Call.ByID(175390889, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopWatchingProject() {
    return $Call.ByID(2423906941);
}

/**
 * @param {string} cwd
 * @returns {$CancellablePromise<void>}
 */
export function SyncBranch(cwd) {
    return $Call.ByID(1685494922, cwd);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function TmuxInstalled() {
    return $Call.ByID(3462207151);
}

/**
 * ToggleProjectService starts a fresh session if not running; stops the
 * project when the last service is removed.
 * @param {string} name
 * @param {string} serviceName
 * @returns {$CancellablePromise<void>}
 */
export function ToggleProjectService(name, serviceName) {
    return $Call.ByID(49964685, name, serviceName);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UninstallKokoro() {
    return $Call.ByID(230895998);
}

/**
 * UploadAndQuoteForTerminal uploads to remote panes; non-remote panes get
 * local-path formatting. Single images stay unquoted so path-detecting
 * receivers can stat them; everything else is shell-quoted.
 * @param {string} terminalID
 * @param {string[]} localPaths
 * @returns {$CancellablePromise<string>}
 */
export function UploadAndQuoteForTerminal(terminalID, localPaths) {
    return $Call.ByID(19813082, terminalID, localPaths);
}

/**
 * @param {string} terminalID
 * @param {string} b64Data
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function UploadClipboardImageForTerminal(terminalID, b64Data, mimeType) {
    return $Call.ByID(3630869162, terminalID, b64Data, mimeType);
}

/**
 * @param {string} passphrase
 * @returns {$CancellablePromise<string>}
 */
export function VaultExportKey(passphrase) {
    return $Call.ByID(2684681676, passphrase);
}

/**
 * VaultImportKey errors if the Keychain already holds a different key
 * (caller must delete it first).
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function VaultImportKey(passphrase) {
    return $Call.ByID(1365533741, passphrase);
}

/**
 * WriteFile preserves existing mode on overwrite; new files use 0644.
 * @param {string} absPath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(absPath, content) {
    return $Call.ByID(3562730546, absPath, content);
}

/**
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(id, data) {
    return $Call.ByID(146795716, id, data);
}

// Private type creation functions
const $$createType0 = $models.PortForward.createFrom;
const $$createType1 = $models.AICLIAvailability.createFrom;
const $$createType2 = $models.PortConflictInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ClaudeHooksStatus.createFrom;
const $$createType5 = $models.UpdateInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.ProjectInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.ChangedFile.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.BranchCommit.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $models.GitStatus.createFrom;
const $$createType16 = $models.ImportReport.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.Branch.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.OpenInTarget.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Array($$createType0);
const $$createType23 = $Create.Array($$createType7);
const $$createType24 = $models.SSHConfigHost.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $models.TemplateInfo.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = $models.Settings.createFrom;
const $$createType29 = $models.TerminalsConfig.createFrom;
const $$createType30 = notes$0.Message.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = notes$0.Chat.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = $Create.Array($$createType32);
const $$createType35 = $Create.Array($$createType30);
const $$createType36 = $models.NotesAttachmentInput.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = notes$0.SearchHit.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $models.TerminalLaunch.createFrom;
