// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AICLIAvailability {
    /**
     * Creates a new AICLIAvailability instance.
     * @param {Partial<AICLIAvailability>} [$$source = {}] - The source object to create the AICLIAvailability.
     */
    constructor($$source = {}) {
        if (!("claude" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["claude"] = false;
        }
        if (!("codex" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["codex"] = false;
        }
        if (!("gemini" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["gemini"] = false;
        }
        if (!("opencode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["opencode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AICLIAvailability instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AICLIAvailability}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AICLIAvailability(/** @type {Partial<AICLIAvailability>} */($$parsedSource));
    }
}

export class ActionInfo {
    /**
     * Creates a new ActionInfo instance.
     * @param {Partial<ActionInfo>} [$$source = {}] - The source object to create the ActionInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cmd"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["env"] = undefined;
        }
        if (!("confirm" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirm"] = false;
        }
        if (!("display" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("reuse" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reuse"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["position"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ActionInputInfo[] | undefined}
             */
            this["inputs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ActionInfo[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField5_0($$parsedSource["env"]);
        }
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField11_0($$parsedSource["inputs"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField12_0($$parsedSource["children"]);
        }
        return new ActionInfo(/** @type {Partial<ActionInfo>} */($$parsedSource));
    }
}

export class ActionInputInfo {
    /**
     * Creates a new ActionInputInfo instance.
     * @param {Partial<ActionInputInfo>} [$$source = {}] - The source object to create the ActionInputInfo.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ActionInputOption[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionInputInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionInputInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new ActionInputInfo(/** @type {Partial<ActionInputInfo>} */($$parsedSource));
    }
}

export class ActionInputOption {
    /**
     * Creates a new ActionInputOption instance.
     * @param {Partial<ActionInputOption>} [$$source = {}] - The source object to create the ActionInputOption.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionInputOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionInputOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionInputOption(/** @type {Partial<ActionInputOption>} */($$parsedSource));
    }
}

export class Branch {
    /**
     * Creates a new Branch instance.
     * @param {Partial<Branch>} [$$source = {}] - The source object to create the Branch.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("committerDate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["committerDate"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Remote is set only for remote-only branches with no matching local head.
             * @member
             * @type {string | undefined}
             */
            this["remote"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Branch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Branch(/** @type {Partial<Branch>} */($$parsedSource));
    }
}

export class BranchCommit {
    /**
     * Creates a new BranchCommit instance.
     * @param {Partial<BranchCommit>} [$$source = {}] - The source object to create the BranchCommit.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchCommit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchCommit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchCommit(/** @type {Partial<BranchCommit>} */($$parsedSource));
    }
}

export class ChangedFile {
    /**
     * Creates a new ChangedFile instance.
     * @param {Partial<ChangedFile>} [$$source = {}] - The source object to create the ChangedFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "modified", "added", "deleted", "renamed", "untracked"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("staged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["staged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangedFile(/** @type {Partial<ChangedFile>} */($$parsedSource));
    }
}

export class ClaudeHooksStatus {
    /**
     * Creates a new ClaudeHooksStatus instance.
     * @param {Partial<ClaudeHooksStatus>} [$$source = {}] - The source object to create the ClaudeHooksStatus.
     */
    constructor($$source = {}) {
        if (!("settingsExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["settingsExists"] = false;
        }
        if (!("hooksInstalled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hooksInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeHooksStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClaudeHooksStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeHooksStatus(/** @type {Partial<ClaudeHooksStatus>} */($$parsedSource));
    }
}

export class DetachedWindowState {
    /**
     * Creates a new DetachedWindowState instance.
     * @param {Partial<DetachedWindowState>} [$$source = {}] - The source object to create the DetachedWindowState.
     */
    constructor($$source = {}) {
        if (!("detached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detached"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["x"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["y"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetachedWindowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetachedWindowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetachedWindowState(/** @type {Partial<DetachedWindowState>} */($$parsedSource));
    }
}

export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("detached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detached"] = false;
        }
        if (!("uncommitted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uncommitted"] = 0;
        }
        if (!("isGitRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isGitRepo"] = false;
        }
        if (!("hasUpstream" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpstream"] = false;
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startCmd"] = undefined;
        }
        if (!("resumeCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resumeCmd"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actionName"] = undefined;
        }
        if (!("closedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["closedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

export class ImportReport {
    /**
     * Creates a new ImportReport instance.
     * @param {Partial<ImportReport>} [$$source = {}] - The source object to create the ImportReport.
     */
    constructor($$source = {}) {
        if (!("imported" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["imported"] = [];
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skipped"] = [];
        }
        if (!("missingRoots" in $$source)) {
            /**
             * @member
             * @type {MissingRoot[]}
             */
            this["missingRoots"] = [];
        }
        if (!("missingTools" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["missingTools"] = [];
        }
        if (!("backupPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imported" in $$parsedSource) {
            $$parsedSource["imported"] = $$createField0_0($$parsedSource["imported"]);
        }
        if ("skipped" in $$parsedSource) {
            $$parsedSource["skipped"] = $$createField1_0($$parsedSource["skipped"]);
        }
        if ("missingRoots" in $$parsedSource) {
            $$parsedSource["missingRoots"] = $$createField2_0($$parsedSource["missingRoots"]);
        }
        if ("missingTools" in $$parsedSource) {
            $$parsedSource["missingTools"] = $$createField3_0($$parsedSource["missingTools"]);
        }
        return new ImportReport(/** @type {Partial<ImportReport>} */($$parsedSource));
    }
}

export class MissingRoot {
    /**
     * Creates a new MissingRoot instance.
     * @param {Partial<MissingRoot>} [$$source = {}] - The source object to create the MissingRoot.
     */
    constructor($$source = {}) {
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MissingRoot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MissingRoot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MissingRoot(/** @type {Partial<MissingRoot>} */($$parsedSource));
    }
}

/**
 * NotesAttachmentInput: Data is base64 (std, padded). Wails' []byte handling
 * is a type-only lie (generated TS says Array<number> but Go json.Marshal
 * emits a base64 string), so we use an explicit string to avoid the mismatch.
 */
export class NotesAttachmentInput {
    /**
     * Creates a new NotesAttachmentInput instance.
     * @param {Partial<NotesAttachmentInput>} [$$source = {}] - The source object to create the NotesAttachmentInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotesAttachmentInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotesAttachmentInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotesAttachmentInput(/** @type {Partial<NotesAttachmentInput>} */($$parsedSource));
    }
}

export class OpenInTarget {
    /**
     * Creates a new OpenInTarget instance.
     * @param {Partial<OpenInTarget>} [$$source = {}] - The source object to create the OpenInTarget.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["fileOnly"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenInTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenInTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenInTarget(/** @type {Partial<OpenInTarget>} */($$parsedSource));
    }
}

/**
 * PaneNode is one node of a persisted pane layout tree.
 * Kind="leaf" uses Tabs/ActiveTabIdx; Kind="split" uses Direction/Ratio/A/B.
 */
export class PaneNode {
    /**
     * Creates a new PaneNode instance.
     * @param {Partial<PaneNode>} [$$source = {}] - The source object to create the PaneNode.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PersistedTab[] | undefined}
             */
            this["tabs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["activeTabIdx"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["activeServiceName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["direction"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ratio"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PaneNode | null | undefined}
             */
            this["a"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PaneNode | null | undefined}
             */
            this["b"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaneNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaneNode}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType11;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        if ("a" in $$parsedSource) {
            $$parsedSource["a"] = $$createField6_0($$parsedSource["a"]);
        }
        if ("b" in $$parsedSource) {
            $$parsedSource["b"] = $$createField7_0($$parsedSource["b"]);
        }
        return new PaneNode(/** @type {Partial<PaneNode>} */($$parsedSource));
    }
}

/**
 * PersistedTab: PTY id is not persisted; StartCmd/ResumeCmd are
 * re-injected on restore.
 */
export class PersistedTab {
    /**
     * Creates a new PersistedTab instance.
     * @param {Partial<PersistedTab>} [$$source = {}] - The source object to create the PersistedTab.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startCmd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resumeCmd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actionName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["pinned"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistedTab instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PersistedTab}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PersistedTab(/** @type {Partial<PersistedTab>} */($$parsedSource));
    }
}

/**
 * PortConflictInfo: PID=0 when the holder isn't identifiable; LpmProject
 * is empty for external processes.
 */
export class PortConflictInfo {
    /**
     * Creates a new PortConflictInfo instance.
     * @param {Partial<PortConflictInfo>} [$$source = {}] - The source object to create the PortConflictInfo.
     */
    constructor($$source = {}) {
        if (!("service" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("process" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["process"] = "";
        }
        if (!("lpmProject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lpmProject"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortConflictInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortConflictInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortConflictInfo(/** @type {Partial<PortConflictInfo>} */($$parsedSource));
    }
}

export class PortForward {
    /**
     * Creates a new PortForward instance.
     * @param {Partial<PortForward>} [$$source = {}] - The source object to create the PortForward.
     */
    constructor($$source = {}) {
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForward(/** @type {Partial<PortForward>} */($$parsedSource));
    }
}

export class ProfileInfo {
    /**
     * Creates a new ProfileInfo instance.
     * @param {Partial<ProfileInfo>} [$$source = {}] - The source object to create the ProfileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("services" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["services"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField1_0($$parsedSource["services"]);
        }
        return new ProfileInfo(/** @type {Partial<ProfileInfo>} */($$parsedSource));
    }
}

export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session"] = "";
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("services" in $$source)) {
            /**
             * @member
             * @type {ServiceInfo[]}
             */
            this["services"] = [];
        }
        if (!("allServices" in $$source)) {
            /**
             * @member
             * @type {ServiceInfo[]}
             */
            this["allServices"] = [];
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {ActionInfo[]}
             */
            this["actions"] = [];
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {ProfileInfo[]}
             */
            this["profiles"] = [];
        }
        if (!("activeProfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeProfile"] = "";
        }
        if (!("statusEntries" in $$source)) {
            /**
             * @member
             * @type {StatusEntry[]}
             */
            this["statusEntries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["configError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentName"] = undefined;
        }
        if (!("isRemote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRemote"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType15;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType17;
        const $$createField10_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField5_0($$parsedSource["services"]);
        }
        if ("allServices" in $$parsedSource) {
            $$parsedSource["allServices"] = $$createField6_0($$parsedSource["allServices"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField8_0($$parsedSource["profiles"]);
        }
        if ("statusEntries" in $$parsedSource) {
            $$parsedSource["statusEntries"] = $$createField10_0($$parsedSource["statusEntries"]);
        }
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

export class ProjectTerminalState {
    /**
     * Creates a new ProjectTerminalState instance.
     * @param {Partial<ProjectTerminalState>} [$$source = {}] - The source object to create the ProjectTerminalState.
     */
    constructor($$source = {}) {
        if (!("detailView" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detailView"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["activeTab"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PaneNode | null | undefined}
             */
            this["panes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["focusedPanePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TerminalEntry[] | undefined}
             */
            this["terminals"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HistoryEntry[] | undefined}
             */
            this["history"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectTerminalState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectTerminalState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType20;
        const $$createField4_0 = $$createType22;
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("panes" in $$parsedSource) {
            $$parsedSource["panes"] = $$createField2_0($$parsedSource["panes"]);
        }
        if ("focusedPanePath" in $$parsedSource) {
            $$parsedSource["focusedPanePath"] = $$createField3_0($$parsedSource["focusedPanePath"]);
        }
        if ("terminals" in $$parsedSource) {
            $$parsedSource["terminals"] = $$createField4_0($$parsedSource["terminals"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField5_0($$parsedSource["history"]);
        }
        return new ProjectTerminalState(/** @type {Partial<ProjectTerminalState>} */($$parsedSource));
    }
}

/**
 * SSHConfig mirrors config.SSHSettings so the frontend can build it directly.
 */
export class SSHConfig {
    /**
     * Creates a new SSHConfig instance.
     * @param {Partial<SSHConfig>} [$$source = {}] - The source object to create the SSHConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig(/** @type {Partial<SSHConfig>} */($$parsedSource));
    }
}

/**
 * SSHConfigHost: HostName falls back to Name when the directive is absent.
 */
export class SSHConfigHost {
    /**
     * Creates a new SSHConfigHost instance.
     * @param {Partial<SSHConfigHost>} [$$source = {}] - The source object to create the SSHConfigHost.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("identityFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["identityFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigHost instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigHost}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigHost(/** @type {Partial<SSHConfigHost>} */($$parsedSource));
    }
}

export class ServiceInfo {
    /**
     * Creates a new ServiceInfo instance.
     * @param {Partial<ServiceInfo>} [$$source = {}] - The source object to create the ServiceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cmd"] = "";
        }
        if (!("cwd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cwd"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["env"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServiceInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        return new ServiceInfo(/** @type {Partial<ServiceInfo>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("doubleClickToToggle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["doubleClickToToggle"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["soundNotifications"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["projectOrder"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["terminalTheme"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["terminalFontSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["terminalOpenInDefaultApp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["editorFontSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["windowHeight"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sidebarWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["autoGenerateCommitMessage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["autoGeneratePRDescription"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["aiCli"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["aiModel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["aiEffort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["aiFast"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["configEditorMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["showProjectName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSelectedProject"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gitPullStrategy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["experimentalTTS"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ttsEnabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ttsVoice"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ttsSpeed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["preferredEditor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DetachedWindows: bounds persist after re-attach so re-detaching
             * restores the previous geometry.
             * @member
             * @type {{ [_ in string]?: DetachedWindowState } | undefined}
             */
            this["detachedWindows"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField26_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projectOrder" in $$parsedSource) {
            $$parsedSource["projectOrder"] = $$createField3_0($$parsedSource["projectOrder"]);
        }
        if ("detachedWindows" in $$parsedSource) {
            $$parsedSource["detachedWindows"] = $$createField26_0($$parsedSource["detachedWindows"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class StatusEntry {
    /**
     * Creates a new StatusEntry instance.
     * @param {Partial<StatusEntry>} [$$source = {}] - The source object to create the StatusEntry.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["agentPID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["paneID"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusEntry(/** @type {Partial<StatusEntry>} */($$parsedSource));
    }
}

export class TemplateInfo {
    /**
     * Creates a new TemplateInfo instance.
     * @param {Partial<TemplateInfo>} [$$source = {}] - The source object to create the TemplateInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateInfo(/** @type {Partial<TemplateInfo>} */($$parsedSource));
    }
}

/**
 * TerminalEntry is the legacy pre-pane-tree shape. Loaded for one-time
 * migration on first save, never written back.
 */
export class TerminalEntry {
    /**
     * Creates a new TerminalEntry instance.
     * @param {Partial<TerminalEntry>} [$$source = {}] - The source object to create the TerminalEntry.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startCmd"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resumeCmd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalEntry(/** @type {Partial<TerminalEntry>} */($$parsedSource));
    }
}

/**
 * TerminalLaunch carries the start cmd and, if the program is recognised,
 * the resume form for next launch.
 */
export class TerminalLaunch {
    /**
     * Creates a new TerminalLaunch instance.
     * @param {Partial<TerminalLaunch>} [$$source = {}] - The source object to create the TerminalLaunch.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("startCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startCmd"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resumeCmd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalLaunch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalLaunch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalLaunch(/** @type {Partial<TerminalLaunch>} */($$parsedSource));
    }
}

export class TerminalsConfig {
    /**
     * Creates a new TerminalsConfig instance.
     * @param {Partial<TerminalsConfig>} [$$source = {}] - The source object to create the TerminalsConfig.
     */
    constructor($$source = {}) {
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ProjectTerminalState }}
             */
            this["projects"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalsConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField0_0($$parsedSource["projects"]);
        }
        return new TerminalsConfig(/** @type {Partial<TerminalsConfig>} */($$parsedSource));
    }
}

export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("updateAvail" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateAvail"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ActionInputInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ActionInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ActionInputOption.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = MissingRoot.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PersistedTab.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PaneNode.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = ServiceInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ProfileInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = StatusEntry.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Array($Create.Any);
const $$createType21 = TerminalEntry.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = HistoryEntry.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = DetachedWindowState.createFrom;
const $$createType26 = $Create.Map($Create.Any, $$createType25);
const $$createType27 = ProjectTerminalState.createFrom;
const $$createType28 = $Create.Map($Create.Any, $$createType27);
