// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Attachment is metadata only; the bytes live in the blob store keyed by Hash.
 */
export class Attachment {
    /**
     * Creates a new Attachment instance.
     * @param {Partial<Attachment>} [$$source = {}] - The source object to create the Attachment.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Attachment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment(/** @type {Partial<Attachment>} */($$parsedSource));
    }
}

export class Chat {
    /**
     * Creates a new Chat instance.
     * @param {Partial<Chat>} [$$source = {}] - The source object to create the Chat.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Chat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chat(/** @type {Partial<Chat>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("chatId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chatId"] = "";
        }
        if (!("ts" in $$source)) {
            /**
             * unix millis
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["editedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Attachment[] | undefined}
             */
            this["attachments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField5_0($$parsedSource["attachments"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * SearchHit's Snippet is plain text (not markdown), safe to render without
 * further escaping.
 */
export class SearchHit {
    /**
     * Creates a new SearchHit instance.
     * @param {Partial<SearchHit>} [$$source = {}] - The source object to create the SearchHit.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("chatId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chatId"] = "";
        }
        if (!("chatTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chatTitle"] = "";
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchHit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit(/** @type {Partial<SearchHit>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Attachment.createFrom;
const $$createType1 = $Create.Array($$createType0);
