use crate::config;
use crate::status::{STATUS_DONE, STATUS_ERROR, STATUS_WAITING};
use std::path::PathBuf;
use tauri::{AppHandle, Emitter};
use tauri_plugin_dialog::DialogExt;

/// Carries a status transition to the machines paired with this one, so a host
/// with nobody at it can still be heard. Forwarded verbatim to authed peers
/// (`peer::FORWARDED_EVENTS`); the payload is a `StatusSound` object, and every
/// reader also accepts the bare status value older hosts sent.
pub const STATUS_SOUND_EVENT: &str = "status-sound";

/// What a paired Mac needs to chime and post a banner for a host's agent: the
/// status value plus the names the host shows for the project and the tab, so
/// the banner reads the same as it would on the host's own screen.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Default)]
pub struct StatusSound {
    pub value: String,
    #[serde(default)]
    pub project: String,
    #[serde(default)]
    pub terminal: String,
}

impl StatusSound {
    /// Reads either payload shape: the object above, or the bare value string
    /// a host from before names rode along still emits.
    pub fn from_payload(payload: &serde_json::Value) -> Option<Self> {
        if let Some(value) = payload.as_str() {
            return Some(Self {
                value: value.to_string(),
                ..Self::default()
            });
        }
        serde_json::from_value(payload.clone()).ok()
    }
}

#[cfg(target_os = "macos")]
const SOUND_EXTS: &[&str] = &["aiff"];
#[cfg(all(unix, not(target_os = "macos")))]
const SOUND_EXTS: &[&str] = &["oga", "ogg", "wav"];
#[cfg(windows)]
const SOUND_EXTS: &[&str] = &["wav"];

#[cfg(target_os = "macos")]
const PICKABLE_AUDIO: &[&str] = &["wav", "aiff", "aif", "mp3", "m4a", "aac", "caf", "flac"];
#[cfg(all(unix, not(target_os = "macos")))]
const PICKABLE_AUDIO: &[&str] = &["wav", "oga", "ogg", "flac", "aiff", "aif", "mp3"];
// PlaySound reads WAV only.
#[cfg(windows)]
const PICKABLE_AUDIO: &[&str] = &["wav"];

fn sounds_dir() -> PathBuf {
    #[cfg(target_os = "macos")]
    {
        PathBuf::from("/System/Library/Sounds")
    }
    #[cfg(all(unix, not(target_os = "macos")))]
    {
        PathBuf::from("/usr/share/sounds/freedesktop/stereo")
    }
    #[cfg(windows)]
    {
        std::env::var_os("SystemRoot")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(r"C:\Windows"))
            .join("Media")
    }
}

fn system_sound(name: &str) -> Option<PathBuf> {
    let dir = sounds_dir();
    SOUND_EXTS
        .iter()
        .map(|ext| dir.join(format!("{name}.{ext}")))
        .find(|p| p.is_file())
}

// Generated by assets/sounds/generate.py.
const CHIME_DONE: &[u8] = include_bytes!("../assets/sounds/done.wav");
const CHIME_WAITING: &[u8] = include_bytes!("../assets/sounds/waiting.wav");
const CHIME_ERROR: &[u8] = include_bytes!("../assets/sounds/error.wav");

fn status_meta(value: &str) -> Option<(&'static str, &'static str)> {
    match value {
        STATUS_DONE => Some(("doneSound", "done")),
        STATUS_WAITING => Some(("waitingSound", "waiting")),
        STATUS_ERROR => Some(("errorSound", "error")),
        _ => None,
    }
}

/// A status transition worth hearing, announced wherever someone can hear it.
///
/// On a Mac or any other desktop that's a chime right here. A headless Linux host
/// has no one at it and no audio stack to assume, so instead it hands the
/// transition to the Macs paired with it, which play it where the person actually
/// is. Those Macs apply their own sound settings to it, which is the right owner
/// of that choice: it's their speaker.
pub fn announce_status(app: &AppHandle, project: &str, value: &str, pane_id: &str) {
    if cfg!(target_os = "macos") || !crate::sys::headless() {
        play_status_sound(value);
    } else if status_meta(value).is_some() {
        let sound = StatusSound {
            value: value.to_string(),
            project: config::project_display_name(project),
            terminal: crate::remote::terminal_label(app, pane_id).unwrap_or_default(),
        };
        let _ = app.emit(STATUS_SOUND_EVENT, sound);
    }
}

pub fn play_status_sound(value: &str) {
    let Some((key, event)) = status_meta(value) else {
        return;
    };
    let settings = config::load_settings();
    if !settings
        .get("soundNotifications")
        .and_then(|v| v.as_bool())
        .unwrap_or(true)
    {
        return;
    }
    let spec = settings
        .get(key)
        .and_then(|v| v.as_str())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or("chime");
    play_spec(spec, event);
}

fn play_spec(spec: &str, event: &str) {
    if spec.eq_ignore_ascii_case("none") {
        return;
    }
    if spec.eq_ignore_ascii_case("chime") {
        if let Some(p) = chime_path(event) {
            play_file(&p);
        }
        return;
    }
    if std::path::Path::new(spec).is_absolute() {
        let p = PathBuf::from(spec);
        if p.is_file() {
            play_file(&p);
        }
        return;
    }
    if is_safe_name(spec) {
        if let Some(p) = system_sound(spec) {
            play_file(&p);
        }
    }
}

#[cfg(target_os = "macos")]
fn play_file(path: &std::path::Path) {
    let _ = std::process::Command::new("afplay").arg(path).spawn();
}

/// Chimes are for the machine a person is sitting at: a headless host's go to
/// the paired Mac and phone instead, so it plays nothing. A desktop plays
/// through whichever player its audio stack ships.
#[cfg(all(unix, not(target_os = "macos")))]
fn play_file(path: &std::path::Path) {
    use std::process::Stdio;
    const PLAYERS: &[(&str, &[&str])] = &[
        ("paplay", &[]),
        ("pw-play", &[]),
        ("canberra-gtk-play", &["-f"]),
        ("aplay", &["-q"]),
    ];
    static PLAYER: std::sync::OnceLock<Option<usize>> = std::sync::OnceLock::new();
    if crate::sys::headless() {
        return;
    }
    let Some(i) =
        *PLAYER.get_or_init(|| PLAYERS.iter().position(|(bin, _)| crate::sys::which(bin)))
    else {
        return;
    };
    let (bin, args) = PLAYERS[i];
    if bin == "aplay" && path.extension().and_then(|e| e.to_str()) != Some("wav") {
        return;
    }
    let spawned = std::process::Command::new(bin)
        .args(args)
        .arg(path)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();
    if let Ok(mut child) = spawned {
        std::thread::spawn(move || {
            let _ = child.wait();
        });
    }
}

#[cfg(windows)]
fn play_file(path: &std::path::Path) {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Media::Audio::{PlaySoundW, SND_ASYNC, SND_FILENAME, SND_NODEFAULT};
    let wide: Vec<u16> = path.as_os_str().encode_wide().chain([0]).collect();
    unsafe {
        PlaySoundW(
            wide.as_ptr(),
            std::ptr::null_mut(),
            SND_FILENAME | SND_ASYNC | SND_NODEFAULT,
        );
    }
}

// Reject anything but a bare name so a system-sound value can't escape the
// sounds folder. Linux and Windows name theirs with dashes and spaces.
fn is_safe_name(name: &str) -> bool {
    !name.is_empty()
        && name.chars().all(|c| {
            c.is_ascii_alphanumeric()
                || (!cfg!(target_os = "macos") && matches!(c, '-' | '_' | ' '))
        })
}

fn chime_bytes(event: &str) -> Option<&'static [u8]> {
    match event {
        "done" => Some(CHIME_DONE),
        "waiting" => Some(CHIME_WAITING),
        "error" => Some(CHIME_ERROR),
        _ => None,
    }
}

// The players need a real path, so extract the embedded chime to ~/.lpm/sounds once.
fn chime_path(event: &str) -> Option<PathBuf> {
    let bytes = chime_bytes(event)?;
    let dir = config::lpm_dir().join("sounds");
    let path = dir.join(format!("{event}.wav"));
    let stale = std::fs::metadata(&path)
        .map(|m| m.len() as usize != bytes.len())
        .unwrap_or(true);
    if stale {
        let _ = std::fs::create_dir_all(&dir);
        if std::fs::write(&path, bytes).is_err() {
            return None;
        }
    }
    Some(path)
}

fn system_sounds() -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(sounds_dir()) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .flatten()
        .filter_map(|e| {
            let p = e.path();
            let ext = p.extension().and_then(|x| x.to_str())?;
            if SOUND_EXTS.contains(&ext) {
                p.file_stem().and_then(|s| s.to_str()).map(String::from)
            } else {
                None
            }
        })
        .collect();
    names.sort();
    names.dedup();
    names
}

#[tauri::command]
pub fn list_system_sounds() -> Vec<String> {
    system_sounds()
}

#[tauri::command]
pub fn play_sound_preview(name: String, event: String) {
    play_spec(&name, &event);
}

#[tauri::command]
pub async fn pick_audio_file(app: AppHandle) -> Result<String, String> {
    let picked = crate::files::pick_path(app, |app| {
        app.dialog()
            .file()
            .set_title("Choose a notification sound")
            .add_filter("Audio", PICKABLE_AUDIO)
            .blocking_pick_file()
    })
    .await?;
    match picked {
        Some(p) => Ok(p.to_string_lossy().into_owned()),
        None => Ok(String::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_meta_maps_notifying_statuses_only() {
        assert_eq!(status_meta(STATUS_DONE), Some(("doneSound", "done")));
        assert_eq!(
            status_meta(STATUS_WAITING),
            Some(("waitingSound", "waiting"))
        );
        assert_eq!(status_meta(STATUS_ERROR), Some(("errorSound", "error")));
        assert_eq!(status_meta("Running"), None);
    }

    #[test]
    fn status_sound_reads_both_payload_shapes() {
        let bare = serde_json::json!("Done");
        assert_eq!(
            StatusSound::from_payload(&bare),
            Some(StatusSound {
                value: "Done".into(),
                ..StatusSound::default()
            })
        );
        let named = serde_json::json!({
            "value": "Waiting",
            "project": "Web App-a1b2c3",
            "terminal": "refactor auth",
        });
        assert_eq!(
            StatusSound::from_payload(&named),
            Some(StatusSound {
                value: "Waiting".into(),
                project: "Web App-a1b2c3".into(),
                terminal: "refactor auth".into(),
            })
        );
        assert_eq!(StatusSound::from_payload(&serde_json::json!(null)), None);
        assert_eq!(
            StatusSound::from_payload(&serde_json::json!({ "project": "x" })),
            None,
            "a value is the one required field"
        );
    }

    #[test]
    fn is_safe_name_blocks_traversal_and_shell() {
        assert!(is_safe_name("Glass"));
        assert!(is_safe_name("Submarine"));
        assert!(!is_safe_name("../../bin/sh"));
        assert!(!is_safe_name("Glass; rm -rf /"));
        assert!(!is_safe_name("Glass.aiff"));
        assert!(!is_safe_name(""));
        assert!(!is_safe_name(r"..\..\Windows\win"));
    }

    #[cfg(not(target_os = "macos"))]
    #[test]
    fn freedesktop_and_windows_sound_names_are_safe() {
        assert!(is_safe_name("dialog-information"));
        assert!(is_safe_name("Windows Notify System Generic"));
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn mac_system_sounds_are_aiff_names() {
        let sounds = system_sounds();
        assert!(sounds.iter().any(|s| s == "Glass"), "{sounds:?}");
        assert_eq!(
            system_sound("Glass"),
            Some(PathBuf::from("/System/Library/Sounds/Glass.aiff"))
        );
    }

    #[test]
    fn embedded_chimes_are_valid_wav() {
        for ev in ["done", "waiting", "error"] {
            let bytes = chime_bytes(ev).unwrap();
            assert!(bytes.len() > 44, "{ev} chime too small");
            assert_eq!(&bytes[0..4], b"RIFF", "{ev} not RIFF");
            assert_eq!(&bytes[8..12], b"WAVE", "{ev} not WAVE");
        }
        assert!(chime_bytes("nope").is_none());
    }
}
