use crate::config;
use crate::status::{STATUS_DONE, STATUS_ERROR, STATUS_WAITING};
use std::path::PathBuf;
use tauri::AppHandle;
use tauri_plugin_dialog::DialogExt;

const SOUNDS_DIR: &str = "/System/Library/Sounds";

// Generated by assets/sounds/generate.py.
const CHIME_DONE: &[u8] = include_bytes!("../assets/sounds/done.wav");
const CHIME_WAITING: &[u8] = include_bytes!("../assets/sounds/waiting.wav");
const CHIME_ERROR: &[u8] = include_bytes!("../assets/sounds/error.wav");

fn status_meta(value: &str) -> Option<(&'static str, &'static str)> {
    match value {
        STATUS_DONE => Some(("doneSound", "done")),
        STATUS_WAITING => Some(("waitingSound", "waiting")),
        STATUS_ERROR => Some(("errorSound", "error")),
        _ => None,
    }
}

pub fn play_status_sound(value: &str) {
    let Some((key, event)) = status_meta(value) else {
        return;
    };
    let settings = config::load_settings();
    if !settings.get("soundNotifications").and_then(|v| v.as_bool()).unwrap_or(false) {
        return;
    }
    let spec = settings
        .get(key)
        .and_then(|v| v.as_str())
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or("chime");
    play_spec(spec, event);
}

fn play_spec(spec: &str, event: &str) {
    if spec.eq_ignore_ascii_case("none") {
        return;
    }
    if spec.eq_ignore_ascii_case("chime") {
        if let Some(p) = chime_path(event) {
            afplay(&p);
        }
        return;
    }
    if spec.starts_with('/') {
        let p = PathBuf::from(spec);
        if p.is_file() {
            afplay(&p);
        }
        return;
    }
    if is_safe_name(spec) {
        let p = PathBuf::from(format!("{SOUNDS_DIR}/{spec}.aiff"));
        if p.is_file() {
            afplay(&p);
        }
    }
}

fn afplay(path: &std::path::Path) {
    let _ = std::process::Command::new("afplay").arg(path).spawn();
}

// Reject anything but a bare word so a system-sound value can't escape SOUNDS_DIR.
fn is_safe_name(name: &str) -> bool {
    !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric())
}

fn chime_bytes(event: &str) -> Option<&'static [u8]> {
    match event {
        "done" => Some(CHIME_DONE),
        "waiting" => Some(CHIME_WAITING),
        "error" => Some(CHIME_ERROR),
        _ => None,
    }
}

// afplay needs a real path, so extract the embedded chime to ~/.lpm/sounds once.
fn chime_path(event: &str) -> Option<PathBuf> {
    let bytes = chime_bytes(event)?;
    let dir = config::lpm_dir().join("sounds");
    let path = dir.join(format!("{event}.wav"));
    let stale = std::fs::metadata(&path).map(|m| m.len() as usize != bytes.len()).unwrap_or(true);
    if stale {
        let _ = std::fs::create_dir_all(&dir);
        if std::fs::write(&path, bytes).is_err() {
            return None;
        }
    }
    Some(path)
}

fn system_sounds() -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(SOUNDS_DIR) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .flatten()
        .filter_map(|e| {
            let p = e.path();
            if p.extension().and_then(|x| x.to_str()) == Some("aiff") {
                p.file_stem().and_then(|s| s.to_str()).map(String::from)
            } else {
                None
            }
        })
        .collect();
    names.sort();
    names
}

#[tauri::command]
pub fn list_system_sounds() -> Vec<String> {
    system_sounds()
}

#[tauri::command]
pub fn play_sound_preview(name: String, event: String) {
    play_spec(&name, &event);
}

// async + spawn_blocking: the blocking picker must not run on the UI thread, or
// the dialog renders but the app freezes (beachball).
#[tauri::command]
pub async fn pick_audio_file(app: AppHandle) -> Result<String, String> {
    let picked = tauri::async_runtime::spawn_blocking(move || {
        app.dialog()
            .file()
            .set_title("Choose a notification sound")
            .add_filter("Audio", &["wav", "aiff", "aif", "mp3", "m4a", "aac", "caf", "flac"])
            .blocking_pick_file()
    })
    .await
    .map_err(|e| e.to_string())?;
    match picked {
        Some(fp) => Ok(fp.into_path().map_err(|e| e.to_string())?.to_string_lossy().into_owned()),
        None => Ok(String::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_meta_maps_notifying_statuses_only() {
        assert_eq!(status_meta(STATUS_DONE), Some(("doneSound", "done")));
        assert_eq!(status_meta(STATUS_WAITING), Some(("waitingSound", "waiting")));
        assert_eq!(status_meta(STATUS_ERROR), Some(("errorSound", "error")));
        assert_eq!(status_meta("Running"), None);
    }

    #[test]
    fn is_safe_name_blocks_traversal_and_shell() {
        assert!(is_safe_name("Glass"));
        assert!(is_safe_name("Submarine"));
        assert!(!is_safe_name("../../bin/sh"));
        assert!(!is_safe_name("Glass; rm -rf /"));
        assert!(!is_safe_name("Glass.aiff"));
        assert!(!is_safe_name(""));
    }

    #[test]
    fn embedded_chimes_are_valid_wav() {
        for ev in ["done", "waiting", "error"] {
            let bytes = chime_bytes(ev).unwrap();
            assert!(bytes.len() > 44, "{ev} chime too small");
            assert_eq!(&bytes[0..4], b"RIFF", "{ev} not RIFF");
            assert_eq!(&bytes[8..12], b"WAVE", "{ev} not WAVE");
        }
        assert!(chime_bytes("nope").is_none());
    }
}
